### PR TITLE
Raspberry Pi Compute Module 4 Support

### PR DESCRIPTION
**Pull request by GeorgeStephens**
Adds support for Raspberry Pi Compute Module 4.
image

### CODE REVIEW

**Comment by StanDeMan** [comment]
@GeorgeStephens 
Compute Module was out of scope so far.
Thanks a lot for your work. Let me check your code. I cannot test it, because no compute module present at my side.
Give me some time - I'll integrate your code soon.

Thanks again and kindest regards
StanDeMan

**Comment by StanDeMan** [comment]
@GeorgeStephens 
I saw your changes. This is fine. It's merged. Have to update the extension for the market place, too.
Thanks a lot + kindets regards
StanDeMan

**Comment by GeorgeStephens** [comment]
Thanks @StanDeMan,

This was tested on a Compute module 4 running Raspberry Pi OS Lite 64-Bit.

I've got a few more minor tweaks as I ran into some similar issues to [Daniel127](https://github.com/Daniel127) [on issue number 8](https://github.com/StanDeMan/RaspberryDebugger/issues/8), I'm not sure they are the right solutions but they are some ideas anyway. Once I've worked through them I'll put them in a branch for you to have a look at though I suspect you'll find a cleaner way to implement.

Items of note:
- I had to install `lsof` as it wasn't installed by default (on Raspberry Pi OS Lite 64-Bit anyway).
- The `Use Proxy` toggle had me confused to start with, it's only as I've debugged the issues I've ran into I've come to understand it. 
- `<PlatformTarget>AnyCPU</PlatformTarget>` and `<RuntimeIdentifier>linux-arm</RuntimeIdentifier>` seems to be required for both ASP.net and console apps from my basic testing.

Thanks for this tool BTW, its really smooth and easy to work with once I got my head round the few points above!

**Comment by StanDeMan** [comment]
@GeorgeStephens 

Jeff Lill is the man - he started this project. 
Some day - if Jeff is willing - he can take all my sources. It's his project. I'm very glad to have this great tool, too. :)

- lsof -> hm? Have to see what this is? Strange. Never had problems with this?
- Use Proxy is for Asp.NET only. For decision if a proxy (NGiNX, Apache, etc.) or Kestrel is used.
- <PlatformTarget>AnyCPU</PlatformTarget> and <RuntimeIdentifier>linux-arm</RuntimeIdentifier> yup! Both are needed, regardeless what type of project you use.

Kindest regard
StanDeMan

**Pull request merged**
